services:
  backend:
    build: ./file-upload-backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build: ./file-upload-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
